FROM scratch
ARG TARGETARCH
COPY bin/docker/${TARGETARCH}/ /
EXPOSE 8080
VOLUME ["/data"]
ENV SPEEDKETCHUP_INTERVAL=10 \
    SPEEDKETCHUP_FILE=/data/speedketchup-results.csv \
    SPEEDKETCHUP_ADDRESS=0.0.0.0 \
    SPEEDKETCHUP_PORT=8080 \
    SPEEDKETCHUP_SERVER= \
    SPEEDKETCHUP_DOWNLOAD_DURATION=10 \
    SPEEDKETCHUP_UPLOAD_DURATION=10 \
    SPEEDKETCHUP_DOWNLOAD_CONNECTIONS=8 \
    SPEEDKETCHUP_UPLOAD_CONNECTIONS=8
ENTRYPOINT ["/speedketchup"]
